// Run: node add_about_terms_keys.js src/translations/index.js
import { readFileSync, writeFileSync } from 'fs';

const path = process.argv[2];
if (!path) { console.error('Usage: node add_about_terms_keys.js <path>'); process.exit(1); }

const keys = {
  en: {
    // About
    aboutWhatTitle:    'What is Recover?',
    aboutWhatBody:     'Recover is a personal harm reduction and recovery support app developed by Qup DA. The app helps you track substance use, mood, and wellbeing for the purpose of harm reduction and recovery support.',
    aboutWhoTitle:     'Who is it for?',
    aboutWhoBody:      'Recover is designed for individuals working through substance use challenges, whether independently or alongside a healthcare provider. It is not a medical device and does not replace professional care.',
    aboutDataTitle:    'Your data',
    aboutDataBody:     'All data you log stays on our secure servers and is never sold to third parties. You may request deletion of your data at any time by contacting us at privacy@qupda.com.',
    aboutDisclaimerTitle: 'Medical disclaimer',
    aboutDisclaimerBody:  'Recover is not a medical device and does not provide medical advice, diagnosis, or treatment. Always consult a qualified healthcare professional for medical concerns.',
    aboutContactTitle: 'Contact',
    aboutContactBody:  'Qup DA\nEmail: support@qupda.com\nWebsite: www.qupda.com',
    // Terms
    termsIntro:        'Please read these Terms and Conditions carefully before using the Recover app.',
    terms1Title:       '1. About the App',
    terms1Body:        'Recover is a personal health tracking application developed by Qup DA. The app is intended to support individuals in monitoring their substance use, mood, and wellbeing for the purpose of harm reduction and recovery support.',
    terms2Title:       '2. Health Data',
    terms2Body:        'By using Recover, you consent to the collection and storage of health-related data. This data is stored securely and used solely to provide you with insights and support within the app.',
    terms3Title:       '3. Privacy Policy',
    terms3Body:        'Qup DA processes your personal data in accordance with GDPR. Your data is never sold to third parties. You may request deletion at any time by contacting privacy@qupda.com.',
    terms4Title:       '4. Medical Disclaimer',
    terms4Body:        'Recover is not a medical device and does not provide medical advice, diagnosis, or treatment. Always consult a qualified healthcare professional for medical concerns.',
    terms5Title:       '5. Data Sharing',
    terms5Body:        'You may choose to share your anonymised data with a healthcare provider through the Share feature. This is always opt-in and can be revoked at any time.',
    terms6Title:       '6. Account Security',
    terms6Body:        'You are responsible for keeping your PIN secure. Qup DA is not liable for unauthorised access resulting from disclosure of your PIN to third parties.',
    terms7Title:       '7. Changes to Terms',
    terms7Body:        'Qup DA reserves the right to update these Terms at any time. Continued use of the app after changes constitutes acceptance of the updated Terms.',
    terms8Title:       '8. Contact',
    terms8Body:        'Qup DA\nEmail: support@qupda.com\nWebsite: www.qupda.com',
  },
  no: {
    aboutWhatTitle:    'Hva er Recover?',
    aboutWhatBody:     'Recover er en personlig skadesreduksjons- og bedringsapp utviklet av Qup DA. Appen hjelper deg å spore rusbruk, humør og velvære.',
    aboutWhoTitle:     'Hvem er den for?',
    aboutWhoBody:      'Recover er designet for personer som jobber med rusutfordringer, enten selvstendig eller sammen med helsepersonell. Det er ikke en medisinsk enhet og erstatter ikke profesjonell omsorg.',
    aboutDataTitle:    'Dine data',
    aboutDataBody:     'All data du logger lagres på våre sikre servere og selges aldri til tredjeparter. Du kan be om sletting av dataene dine ved å kontakte oss på privacy@qupda.com.',
    aboutDisclaimerTitle: 'Medisinsk ansvarsfraskrivelse',
    aboutDisclaimerBody:  'Recover er ikke en medisinsk enhet og gir ikke medisinsk råd, diagnose eller behandling. Konsulter alltid kvalifisert helsepersonell for medisinske bekymringer.',
    aboutContactTitle: 'Kontakt',
    aboutContactBody:  'Qup DA\nE-post: support@qupda.com\nNettside: www.qupda.com',
    termsIntro:        'Les disse vilkårene nøye før du bruker Recover-appen.',
    terms1Title:       '1. Om appen',
    terms1Body:        'Recover er en personlig helseapp utviklet av Qup DA for å støtte skadesreduksjon og bedring.',
    terms2Title:       '2. Helsedata',
    terms2Body:        'Ved å bruke Recover samtykker du til innsamling og lagring av helserelaterte data. Disse brukes utelukkende til å gi deg innsikt og støtte i appen.',
    terms3Title:       '3. Personvernerklæring',
    terms3Body:        'Qup DA behandler dine persondata i henhold til GDPR. Dataene dine selges aldri til tredjeparter. Kontakt privacy@qupda.com for å be om sletting.',
    terms4Title:       '4. Medisinsk ansvarsfraskrivelse',
    terms4Body:        'Recover er ikke en medisinsk enhet og gir ikke råd, diagnose eller behandling. Konsulter alltid helsepersonell.',
    terms5Title:       '5. Datadeling',
    terms5Body:        'Du kan velge å dele anonymiserte data med en helsepersonell via Del-funksjonen. Dette er alltid opt-in og kan trekkes tilbake.',
    terms6Title:       '6. Kontosikkerhet',
    terms6Body:        'Du er ansvarlig for å holde PIN-koden din sikker. Qup DA er ikke ansvarlig for uautorisert tilgang.',
    terms7Title:       '7. Endringer i vilkår',
    terms7Body:        'Qup DA forbeholder seg retten til å oppdatere disse vilkårene. Fortsatt bruk etter endringer innebærer aksept.',
    terms8Title:       '8. Kontakt',
    terms8Body:        'Qup DA\nE-post: support@qupda.com\nNettside: www.qupda.com',
  },
  de: {
    aboutWhatTitle:    'Was ist Recover?',
    aboutWhatBody:     'Recover ist eine persönliche Schadensminimierungs-App, die von Qup DA entwickelt wurde.',
    aboutWhoTitle:     'Für wen ist sie?',
    aboutWhoBody:      'Recover richtet sich an Personen, die Herausforderungen mit Substanzkonsum bewältigen. Es ist kein Medizinprodukt.',
    aboutDataTitle:    'Deine Daten',
    aboutDataBody:     'Alle Daten werden sicher gespeichert und nie an Dritte verkauft. Kontaktiere privacy@qupda.com für eine Löschung.',
    aboutDisclaimerTitle: 'Medizinischer Haftungsausschluss',
    aboutDisclaimerBody:  'Recover ist kein Medizinprodukt. Konsultiere immer einen Arzt bei medizinischen Bedenken.',
    aboutContactTitle: 'Kontakt',
    aboutContactBody:  'Qup DA\nE-Mail: support@qupda.com\nWebsite: www.qupda.com',
    termsIntro:        'Lies diese Nutzungsbedingungen sorgfältig durch, bevor du Recover verwendest.',
    terms1Title:       '1. Über die App',
    terms1Body:        'Recover ist eine von Qup DA entwickelte App zur Unterstützung bei Schadensminimierung und Genesung.',
    terms2Title:       '2. Gesundheitsdaten',
    terms2Body:        'Mit der Nutzung von Recover stimmst du der Erfassung gesundheitsbezogener Daten zu, die ausschließlich zur Unterstützung in der App verwendet werden.',
    terms3Title:       '3. Datenschutz',
    terms3Body:        'Qup DA verarbeitet deine Daten gemäß DSGVO. Deine Daten werden nie verkauft. Kontaktiere privacy@qupda.com für eine Löschung.',
    terms4Title:       '4. Medizinischer Haftungsausschluss',
    terms4Body:        'Recover ist kein Medizinprodukt. Konsultiere immer einen Arzt.',
    terms5Title:       '5. Datenweitergabe',
    terms5Body:        'Du kannst anonymisierte Daten mit einem Arzt teilen. Dies ist immer opt-in.',
    terms6Title:       '6. Kontosicherheit',
    terms6Body:        'Du bist für die Sicherheit deines PINs verantwortlich. Qup DA haftet nicht für unbefugten Zugriff.',
    terms7Title:       '7. Änderungen',
    terms7Body:        'Qup DA behält sich das Recht vor, diese Bedingungen zu aktualisieren.',
    terms8Title:       '8. Kontakt',
    terms8Body:        'Qup DA\nE-Mail: support@qupda.com\nWebsite: www.qupda.com',
  },
  da: {
    aboutWhatTitle:    'Hvad er Recover?',
    aboutWhatBody:     'Recover er en personlig app til skadereduktion og bedring, udviklet af Qup DA.',
    aboutWhoTitle:     'Hvem er den til?',
    aboutWhoBody:      'Recover er designet til personer, der håndterer udfordringer med stofbrug. Det er ikke en medicinsk enhed.',
    aboutDataTitle:    'Dine data',
    aboutDataBody:     'Alle data gemmes sikkert og sælges aldrig til tredjepart. Kontakt privacy@qupda.com for sletning.',
    aboutDisclaimerTitle: 'Medicinsk ansvarsfraskrivelse',
    aboutDisclaimerBody:  'Recover er ikke en medicinsk enhed. Konsulter altid en læge ved medicinske bekymringer.',
    aboutContactTitle: 'Kontakt',
    aboutContactBody:  'Qup DA\nE-mail: support@qupda.com\nHjemmeside: www.qupda.com',
    termsIntro:        'Læs disse vilkår omhyggeligt inden du bruger Recover.',
    terms1Title:       '1. Om appen',
    terms1Body:        'Recover er en app udviklet af Qup DA til støtte af skadereduktion og bedring.',
    terms2Title:       '2. Sundhedsdata',
    terms2Body:        'Ved at bruge Recover accepterer du indsamling af sundhedsrelaterede data udelukkende til brug i appen.',
    terms3Title:       '3. Privatlivspolitik',
    terms3Body:        'Qup DA behandler dine data i overensstemmelse med GDPR. Kontakt privacy@qupda.com for sletning.',
    terms4Title:       '4. Medicinsk ansvarsfraskrivelse',
    terms4Body:        'Recover er ikke en medicinsk enhed. Konsulter altid en læge.',
    terms5Title:       '5. Datadeling',
    terms5Body:        'Du kan dele anonymiserede data med en behandler. Dette er altid opt-in.',
    terms6Title:       '6. Kontosikkerhed',
    terms6Body:        'Du er ansvarlig for sikkerheden af din PIN. Qup DA er ikke ansvarlig for uautoriseret adgang.',
    terms7Title:       '7. Ændringer',
    terms7Body:        'Qup DA forbeholder sig retten til at opdatere disse vilkår.',
    terms8Title:       '8. Kontakt',
    terms8Body:        'Qup DA\nE-mail: support@qupda.com\nHjemmeside: www.qupda.com',
  },
  sv: {
    aboutWhatTitle:    'Vad är Recover?',
    aboutWhatBody:     'Recover är en personlig app för skadereducering och tillfrisknande, utvecklad av Qup DA.',
    aboutWhoTitle:     'Vem är den till för?',
    aboutWhoBody:      'Recover är utformad för personer som hanterar utmaningar med substansbruk. Det är ingen medicinsk enhet.',
    aboutDataTitle:    'Dina data',
    aboutDataBody:     'All data lagras säkert och säljs aldrig till tredje part. Kontakta privacy@qupda.com för radering.',
    aboutDisclaimerTitle: 'Medicinskt friskrivningsansvar',
    aboutDisclaimerBody:  'Recover är ingen medicinsk enhet. Konsultera alltid en läkare vid medicinska frågor.',
    aboutContactTitle: 'Kontakt',
    aboutContactBody:  'Qup DA\nE-post: support@qupda.com\nWebbplats: www.qupda.com',
    termsIntro:        'Läs dessa villkor noggrant innan du använder Recover.',
    terms1Title:       '1. Om appen',
    terms1Body:        'Recover är en app utvecklad av Qup DA för stöd vid skadereducering och tillfrisknande.',
    terms2Title:       '2. Hälsodata',
    terms2Body:        'Genom att använda Recover samtycker du till insamling av hälsorelaterade data som enbart används i appen.',
    terms3Title:       '3. Integritetspolicy',
    terms3Body:        'Qup DA behandlar dina uppgifter enligt GDPR. Kontakta privacy@qupda.com för radering.',
    terms4Title:       '4. Medicinskt friskrivningsansvar',
    terms4Body:        'Recover är ingen medicinsk enhet. Konsultera alltid läkare.',
    terms5Title:       '5. Datadelning',
    terms5Body:        'Du kan dela anonymiserade data med en vårdgivare. Detta är alltid opt-in.',
    terms6Title:       '6. Kontosäkerhet',
    terms6Body:        'Du ansvarar för säkerheten för din PIN. Qup DA ansvarar inte för obehörig åtkomst.',
    terms7Title:       '7. Ändringar',
    terms7Body:        'Qup DA förbehåller sig rätten att uppdatera dessa villkor.',
    terms8Title:       '8. Kontakt',
    terms8Body:        'Qup DA\nE-post: support@qupda.com\nWebbplats: www.qupda.com',
  },
  fi: {
    aboutWhatTitle:    'Mikä on Recover?',
    aboutWhatBody:     'Recover on Qup DA:n kehittämä henkilökohtainen haittojen vähentämis- ja toipumissovellus.',
    aboutWhoTitle:     'Kenelle se on tarkoitettu?',
    aboutWhoBody:      'Recover on suunniteltu henkilöille, jotka käsittelevät päihdehaasteita. Se ei ole lääkinnällinen laite.',
    aboutDataTitle:    'Tietosi',
    aboutDataBody:     'Kaikki tiedot tallennetaan turvallisesti eikä niitä myydä kolmansille osapuolille. Ota yhteyttä privacy@qupda.com poistoa varten.',
    aboutDisclaimerTitle: 'Lääketieteellinen vastuuvapauslauseke',
    aboutDisclaimerBody:  'Recover ei ole lääkinnällinen laite. Konsultoi aina terveydenhuollon ammattilaista lääketieteellisissä kysymyksissä.',
    aboutContactTitle: 'Yhteystiedot',
    aboutContactBody:  'Qup DA\nSähköposti: support@qupda.com\nVerkkosivusto: www.qupda.com',
    termsIntro:        'Lue nämä käyttöehdot huolellisesti ennen Recover-sovelluksen käyttöä.',
    terms1Title:       '1. Sovelluksesta',
    terms1Body:        'Recover on Qup DA:n kehittämä sovellus haittojen vähentämisen ja toipumisen tukemiseksi.',
    terms2Title:       '2. Terveystiedot',
    terms2Body:        'Käyttämällä Recoveria suostut terveystietojen keräämiseen yksinomaan sovelluksen tukemiseksi.',
    terms3Title:       '3. Tietosuojakäytäntö',
    terms3Body:        'Qup DA käsittelee henkilötietojasi GDPR:n mukaisesti. Ota yhteyttä privacy@qupda.com poistopyyntöä varten.',
    terms4Title:       '4. Lääketieteellinen vastuuvapauslauseke',
    terms4Body:        'Recover ei ole lääkinnällinen laite. Konsultoi aina lääkäriä.',
    terms5Title:       '5. Tietojen jakaminen',
    terms5Body:        'Voit jakaa anonymisoituja tietoja terveydenhuollon tarjoajalle. Tämä on aina opt-in.',
    terms6Title:       '6. Tilin turvallisuus',
    terms6Body:        'Olet vastuussa PIN-koodisi turvallisuudesta. Qup DA ei vastaa luvattomasta käytöstä.',
    terms7Title:       '7. Muutokset',
    terms7Body:        'Qup DA pidättää oikeuden päivittää näitä ehtoja.',
    terms8Title:       '8. Yhteystiedot',
    terms8Body:        'Qup DA\nSähköposti: support@qupda.com\nVerkkosivusto: www.qupda.com',
  },
  fr: {
    aboutWhatTitle:    'Qu\'est-ce que Recover ?',
    aboutWhatBody:     'Recover est une application personnelle de réduction des risques développée par Qup DA.',
    aboutWhoTitle:     'Pour qui est-elle ?',
    aboutWhoBody:      'Recover est conçue pour les personnes confrontées à des défis liés à la consommation de substances. Ce n\'est pas un dispositif médical.',
    aboutDataTitle:    'Vos données',
    aboutDataBody:     'Toutes les données sont stockées en sécurité et ne sont jamais vendues à des tiers. Contactez privacy@qupda.com pour une suppression.',
    aboutDisclaimerTitle: 'Avertissement médical',
    aboutDisclaimerBody:  'Recover n\'est pas un dispositif médical. Consultez toujours un professionnel de santé.',
    aboutContactTitle: 'Contact',
    aboutContactBody:  'Qup DA\nE-mail : support@qupda.com\nSite web : www.qupda.com',
    termsIntro:        'Lisez attentivement ces conditions avant d\'utiliser Recover.',
    terms1Title:       '1. À propos de l\'application',
    terms1Body:        'Recover est une application développée par Qup DA pour soutenir la réduction des risques et le rétablissement.',
    terms2Title:       '2. Données de santé',
    terms2Body:        'En utilisant Recover, vous consentez à la collecte de données de santé utilisées uniquement dans l\'application.',
    terms3Title:       '3. Politique de confidentialité',
    terms3Body:        'Qup DA traite vos données conformément au RGPD. Contactez privacy@qupda.com pour une suppression.',
    terms4Title:       '4. Avertissement médical',
    terms4Body:        'Recover n\'est pas un dispositif médical. Consultez toujours un médecin.',
    terms5Title:       '5. Partage de données',
    terms5Body:        'Vous pouvez partager des données anonymisées avec un professionnel de santé. Ceci est toujours opt-in.',
    terms6Title:       '6. Sécurité du compte',
    terms6Body:        'Vous êtes responsable de la sécurité de votre PIN. Qup DA n\'est pas responsable d\'un accès non autorisé.',
    terms7Title:       '7. Modifications',
    terms7Body:        'Qup DA se réserve le droit de mettre à jour ces conditions.',
    terms8Title:       '8. Contact',
    terms8Body:        'Qup DA\nE-mail : support@qupda.com\nSite web : www.qupda.com',
  },
  es: {
    aboutWhatTitle:    '¿Qué es Recover?',
    aboutWhatBody:     'Recover es una app personal de reducción de daños desarrollada por Qup DA.',
    aboutWhoTitle:     '¿Para quién es?',
    aboutWhoBody:      'Recover está diseñada para personas que enfrentan desafíos con el consumo de sustancias. No es un dispositivo médico.',
    aboutDataTitle:    'Tus datos',
    aboutDataBody:     'Todos los datos se almacenan de forma segura y nunca se venden a terceros. Contacta privacy@qupda.com para solicitar eliminación.',
    aboutDisclaimerTitle: 'Aviso médico',
    aboutDisclaimerBody:  'Recover no es un dispositivo médico. Consulta siempre a un profesional de salud.',
    aboutContactTitle: 'Contacto',
    aboutContactBody:  'Qup DA\nEmail: support@qupda.com\nWeb: www.qupda.com',
    termsIntro:        'Lee estos términos detenidamente antes de usar Recover.',
    terms1Title:       '1. Sobre la app',
    terms1Body:        'Recover es una app desarrollada por Qup DA para apoyar la reducción de daños y la recuperación.',
    terms2Title:       '2. Datos de salud',
    terms2Body:        'Al usar Recover, consientes la recopilación de datos de salud usados únicamente en la app.',
    terms3Title:       '3. Política de privacidad',
    terms3Body:        'Qup DA procesa tus datos conforme al RGPD. Contacta privacy@qupda.com para eliminar tus datos.',
    terms4Title:       '4. Aviso médico',
    terms4Body:        'Recover no es un dispositivo médico. Consulta siempre a un médico.',
    terms5Title:       '5. Compartir datos',
    terms5Body:        'Puedes compartir datos anonimizados con un proveedor de salud. Esto es siempre opt-in.',
    terms6Title:       '6. Seguridad de la cuenta',
    terms6Body:        'Eres responsable de mantener tu PIN seguro. Qup DA no es responsable del acceso no autorizado.',
    terms7Title:       '7. Cambios',
    terms7Body:        'Qup DA se reserva el derecho de actualizar estos términos.',
    terms8Title:       '8. Contacto',
    terms8Body:        'Qup DA\nEmail: support@qupda.com\nWeb: www.qupda.com',
  },
  it: {
    aboutWhatTitle:    "Cos'è Recover?",
    aboutWhatBody:     'Recover è un\'app personale di riduzione del danno sviluppata da Qup DA.',
    aboutWhoTitle:     'Per chi è?',
    aboutWhoBody:      'Recover è progettata per persone che affrontano sfide legate all\'uso di sostanze. Non è un dispositivo medico.',
    aboutDataTitle:    'I tuoi dati',
    aboutDataBody:     'Tutti i dati sono archiviati in modo sicuro e non vengono mai venduti a terzi. Contatta privacy@qupda.com per la cancellazione.',
    aboutDisclaimerTitle: 'Avvertenza medica',
    aboutDisclaimerBody:  'Recover non è un dispositivo medico. Consulta sempre un professionista sanitario.',
    aboutContactTitle: 'Contatto',
    aboutContactBody:  'Qup DA\nEmail: support@qupda.com\nSito web: www.qupda.com',
    termsIntro:        'Leggi attentamente questi termini prima di usare Recover.',
    terms1Title:       "1. Sull'app",
    terms1Body:        'Recover è un\'app sviluppata da Qup DA per supportare la riduzione del danno e il recupero.',
    terms2Title:       '2. Dati sanitari',
    terms2Body:        'Utilizzando Recover, acconsenti alla raccolta di dati sanitari usati esclusivamente nell\'app.',
    terms3Title:       '3. Privacy',
    terms3Body:        'Qup DA tratta i tuoi dati in conformità con il GDPR. Contatta privacy@qupda.com per la cancellazione.',
    terms4Title:       '4. Avvertenza medica',
    terms4Body:        'Recover non è un dispositivo medico. Consulta sempre un medico.',
    terms5Title:       '5. Condivisione dati',
    terms5Body:        'Puoi condividere dati anonimizzati con un operatore sanitario. Questo è sempre opt-in.',
    terms6Title:       '6. Sicurezza account',
    terms6Body:        'Sei responsabile della sicurezza del tuo PIN. Qup DA non è responsabile per accessi non autorizzati.',
    terms7Title:       '7. Modifiche',
    terms7Body:        'Qup DA si riserva il diritto di aggiornare questi termini.',
    terms8Title:       '8. Contatto',
    terms8Body:        'Qup DA\nEmail: support@qupda.com\nSito web: www.qupda.com',
  },
  nl: {
    aboutWhatTitle:    'Wat is Recover?',
    aboutWhatBody:     'Recover is een persoonlijke app voor schadebeperking en herstel, ontwikkeld door Qup DA.',
    aboutWhoTitle:     'Voor wie is het?',
    aboutWhoBody:      'Recover is ontworpen voor mensen die uitdagingen met middelengebruik aanpakken. Het is geen medisch hulpmiddel.',
    aboutDataTitle:    'Jouw gegevens',
    aboutDataBody:     'Alle gegevens worden veilig opgeslagen en nooit verkocht aan derden. Neem contact op met privacy@qupda.com voor verwijdering.',
    aboutDisclaimerTitle: 'Medische disclaimer',
    aboutDisclaimerBody:  'Recover is geen medisch hulpmiddel. Raadpleeg altijd een zorgprofessional.',
    aboutContactTitle: 'Contact',
    aboutContactBody:  'Qup DA\nE-mail: support@qupda.com\nWebsite: www.qupda.com',
    termsIntro:        'Lees deze voorwaarden zorgvuldig door voordat je Recover gebruikt.',
    terms1Title:       '1. Over de app',
    terms1Body:        'Recover is een app ontwikkeld door Qup DA ter ondersteuning van schadebeperking en herstel.',
    terms2Title:       '2. Gezondheidsgegevens',
    terms2Body:        'Door Recover te gebruiken, stem je in met het verzamelen van gezondheidsgegevens die uitsluitend in de app worden gebruikt.',
    terms3Title:       '3. Privacybeleid',
    terms3Body:        'Qup DA verwerkt je gegevens conform de AVG. Neem contact op met privacy@qupda.com voor verwijdering.',
    terms4Title:       '4. Medische disclaimer',
    terms4Body:        'Recover is geen medisch hulpmiddel. Raadpleeg altijd een arts.',
    terms5Title:       '5. Gegevens delen',
    terms5Body:        'Je kunt geanonimiseerde gegevens delen met een zorgverlener. Dit is altijd opt-in.',
    terms6Title:       '6. Accountbeveiliging',
    terms6Body:        'Je bent verantwoordelijk voor de veiligheid van je PIN. Qup DA is niet aansprakelijk voor ongeautoriseerde toegang.',
    terms7Title:       '7. Wijzigingen',
    terms7Body:        'Qup DA behoudt zich het recht voor deze voorwaarden te updaten.',
    terms8Title:       '8. Contact',
    terms8Body:        'Qup DA\nE-mail: support@qupda.com\nWebsite: www.qupda.com',
  },
  pl: {
    aboutWhatTitle:    'Czym jest Recover?',
    aboutWhatBody:     'Recover to osobista aplikacja do ograniczania szkód i zdrowienia, opracowana przez Qup DA.',
    aboutWhoTitle:     'Dla kogo jest?',
    aboutWhoBody:      'Recover jest przeznaczony dla osób zmagających się z uzależnieniami. Nie jest urządzeniem medycznym.',
    aboutDataTitle:    'Twoje dane',
    aboutDataBody:     'Wszystkie dane są bezpiecznie przechowywane i nigdy nie sprzedawane stronom trzecim. Skontaktuj się z privacy@qupda.com w sprawie usunięcia.',
    aboutDisclaimerTitle: 'Zastrzeżenie medyczne',
    aboutDisclaimerBody:  'Recover nie jest urządzeniem medycznym. Zawsze konsultuj się z lekarzem w sprawach medycznych.',
    aboutContactTitle: 'Kontakt',
    aboutContactBody:  'Qup DA\nE-mail: support@qupda.com\nStrona: www.qupda.com',
    termsIntro:        'Przeczytaj uważnie te warunki przed użyciem Recover.',
    terms1Title:       '1. O aplikacji',
    terms1Body:        'Recover to aplikacja opracowana przez Qup DA wspierająca ograniczanie szkód i zdrowienie.',
    terms2Title:       '2. Dane zdrowotne',
    terms2Body:        'Korzystając z Recover, wyrażasz zgodę na zbieranie danych zdrowotnych używanych wyłącznie w aplikacji.',
    terms3Title:       '3. Polityka prywatności',
    terms3Body:        'Qup DA przetwarza Twoje dane zgodnie z RODO. Skontaktuj się z privacy@qupda.com w sprawie usunięcia.',
    terms4Title:       '4. Zastrzeżenie medyczne',
    terms4Body:        'Recover nie jest urządzeniem medycznym. Zawsze konsultuj się z lekarzem.',
    terms5Title:       '5. Udostępnianie danych',
    terms5Body:        'Możesz udostępniać anonimizowane dane świadczeniodawcy opieki zdrowotnej. Jest to zawsze opt-in.',
    terms6Title:       '6. Bezpieczeństwo konta',
    terms6Body:        'Jesteś odpowiedzialny za bezpieczeństwo swojego PIN-u. Qup DA nie ponosi odpowiedzialności za nieautoryzowany dostęp.',
    terms7Title:       '7. Zmiany',
    terms7Body:        'Qup DA zastrzega sobie prawo do aktualizacji tych warunków.',
    terms8Title:       '8. Kontakt',
    terms8Body:        'Qup DA\nE-mail: support@qupda.com\nStrona: www.qupda.com',
  },
  pt: {
    aboutWhatTitle:    'O que é o Recover?',
    aboutWhatBody:     'Recover é um app pessoal de redução de danos desenvolvido pela Qup DA.',
    aboutWhoTitle:     'Para quem é?',
    aboutWhoBody:      'Recover é projetado para pessoas que enfrentam desafios com o uso de substâncias. Não é um dispositivo médico.',
    aboutDataTitle:    'Seus dados',
    aboutDataBody:     'Todos os dados são armazenados com segurança e nunca vendidos a terceiros. Entre em contato com privacy@qupda.com para exclusão.',
    aboutDisclaimerTitle: 'Aviso médico',
    aboutDisclaimerBody:  'Recover não é um dispositivo médico. Consulte sempre um profissional de saúde.',
    aboutContactTitle: 'Contato',
    aboutContactBody:  'Qup DA\nEmail: support@qupda.com\nSite: www.qupda.com',
    termsIntro:        'Leia estes termos com atenção antes de usar o Recover.',
    terms1Title:       '1. Sobre o app',
    terms1Body:        'Recover é um app desenvolvido pela Qup DA para apoiar a redução de danos e a recuperação.',
    terms2Title:       '2. Dados de saúde',
    terms2Body:        'Ao usar o Recover, você consente com a coleta de dados de saúde usados exclusivamente no app.',
    terms3Title:       '3. Política de privacidade',
    terms3Body:        'Qup DA processa seus dados em conformidade com o GDPR. Entre em contato com privacy@qupda.com para exclusão.',
    terms4Title:       '4. Aviso médico',
    terms4Body:        'Recover não é um dispositivo médico. Consulte sempre um médico.',
    terms5Title:       '5. Compartilhamento de dados',
    terms5Body:        'Você pode compartilhar dados anonimizados com um profissional de saúde. Isso é sempre opt-in.',
    terms6Title:       '6. Segurança da conta',
    terms6Body:        'Você é responsável pela segurança do seu PIN. Qup DA não é responsável por acesso não autorizado.',
    terms7Title:       '7. Alterações',
    terms7Body:        'Qup DA reserva-se o direito de atualizar estes termos.',
    terms8Title:       '8. Contato',
    terms8Body:        'Qup DA\nEmail: support@qupda.com\nSite: www.qupda.com',
  },
};

let src = readFileSync(path, 'utf8');
let injected = 0;

for (const [lang, langKeys] of Object.entries(keys)) {
  const langStart = src.indexOf(`const ${lang} = {`);
  if (langStart === -1) { console.warn(`Lang not found: ${lang}`); continue; }

  let depth = 0, closeIdx = -1;
  for (let i = langStart; i < src.length; i++) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') { depth--; if (depth === 0) { closeIdx = i; break; } }
  }
  if (closeIdx === -1) { console.warn(`No closing brace: ${lang}`); continue; }

  const objSrc = src.slice(langStart, closeIdx + 1);
  const toInject = [];
  for (const [key, val] of Object.entries(langKeys)) {
    const keyPattern = new RegExp(`[\\s,]${key}\\s*:`);
    if (!keyPattern.test(objSrc)) {
      toInject.push(`  ${key}: ${JSON.stringify(val)},`);
      injected++;
    }
  }

  if (toInject.length > 0) {
    const insertion = '\n' + toInject.join('\n') + '\n';
    src = src.slice(0, closeIdx) + insertion + src.slice(closeIdx);
  }
}

writeFileSync(path, src, 'utf8');
console.log(`Done. Injected ${injected} keys.`);
